! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc99_mosaic_4bin_iepox_vbs_aq_Parameters.f90
! Time                 : Tue Jan 11 14:33:23 2022
! Working directory    : /jathar-scratch/yicongh/WRF_GoAmazon_gasaerochem.DEV/chem/KPP/mechanisms/saprc99_mosaic_4bin_iepox_vbs_aq
! Equation file        : saprc99_mosaic_4bin_iepox_vbs_aq.kpp
! Output root filename : saprc99_mosaic_4bin_iepox_vbs_aq
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc99_mosaic_4bin_iepox_vbs_aq_Parameters

  USE saprc99_mosaic_4bin_iepox_vbs_aq_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 120 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 118 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 93 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 2 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 289 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 119 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1084 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1165 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 119 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 
! PI - Value of pi
  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_H2SO4 = 1 
  INTEGER, PARAMETER :: ind_HCOOH = 2 
  INTEGER, PARAMETER :: ind_CCO_OH = 3 
  INTEGER, PARAMETER :: ind_RCO_OH = 4 
  INTEGER, PARAMETER :: ind_CO2 = 5 
  INTEGER, PARAMETER :: ind_CCO_OOH = 6 
  INTEGER, PARAMETER :: ind_RCO_OOH = 7 
  INTEGER, PARAMETER :: ind_XN = 8 
  INTEGER, PARAMETER :: ind_XC = 9 
  INTEGER, PARAMETER :: ind_NUME = 10 
  INTEGER, PARAMETER :: ind_DEN = 11 
  INTEGER, PARAMETER :: ind_ANT1_c = 12 
  INTEGER, PARAMETER :: ind_ANT2_o = 13 
  INTEGER, PARAMETER :: ind_ANT3_o = 14 
  INTEGER, PARAMETER :: ind_BIOG1_c = 15 
  INTEGER, PARAMETER :: ind_BIOG1_o = 16 
  INTEGER, PARAMETER :: ind_PSD1 = 17 
  INTEGER, PARAMETER :: ind_ISOP2O2 = 18 
  INTEGER, PARAMETER :: ind_IEPOX = 19 
  INTEGER, PARAMETER :: ind_TETROL = 20 
  INTEGER, PARAMETER :: ind_OPCG2_F_O = 21 
  INTEGER, PARAMETER :: ind_OPCG1_B_O = 22 
  INTEGER, PARAMETER :: ind_OPCG2_B_O = 23 
  INTEGER, PARAMETER :: ind_OPCG3_B_O = 24 
  INTEGER, PARAMETER :: ind_OPCG4_B_O = 25 
  INTEGER, PARAMETER :: ind_PCG7_B_C = 26 
  INTEGER, PARAMETER :: ind_OPCG5_B_O = 27 
  INTEGER, PARAMETER :: ind_OPCG6_B_O = 28 
  INTEGER, PARAMETER :: ind_OPCG7_B_O = 29 
  INTEGER, PARAMETER :: ind_PCG7_B_O = 30 
  INTEGER, PARAMETER :: ind_O1D = 31 
  INTEGER, PARAMETER :: ind_CH4 = 32 
  INTEGER, PARAMETER :: ind_ISOPOOH = 33 
  INTEGER, PARAMETER :: ind_ISOPOO = 34 
  INTEGER, PARAMETER :: ind_C2H6 = 35 
  INTEGER, PARAMETER :: ind_PCG7_F_C = 36 
  INTEGER, PARAMETER :: ind_OPCG3_F_O = 37 
  INTEGER, PARAMETER :: ind_OPCG4_F_O = 38 
  INTEGER, PARAMETER :: ind_OPCG5_F_O = 39 
  INTEGER, PARAMETER :: ind_OPCG6_F_O = 40 
  INTEGER, PARAMETER :: ind_PAN = 41 
  INTEGER, PARAMETER :: ind_PAN2 = 42 
  INTEGER, PARAMETER :: ind_PBZN = 43 
  INTEGER, PARAMETER :: ind_MA_PAN = 44 
  INTEGER, PARAMETER :: ind_BIOG2_c = 45 
  INTEGER, PARAMETER :: ind_BIOG4_c = 46 
  INTEGER, PARAMETER :: ind_BIOG3_c = 47 
  INTEGER, PARAMETER :: ind_H2O2 = 48 
  INTEGER, PARAMETER :: ind_ANT2_c = 49 
  INTEGER, PARAMETER :: ind_ANT3_c = 50 
  INTEGER, PARAMETER :: ind_ANT4_c = 51 
  INTEGER, PARAMETER :: ind_BIOG2_o = 52 
  INTEGER, PARAMETER :: ind_BIOG3_o = 53 
  INTEGER, PARAMETER :: ind_BIOG4_o = 54 
  INTEGER, PARAMETER :: ind_ETOH = 55 
  INTEGER, PARAMETER :: ind_C3H8 = 56 
  INTEGER, PARAMETER :: ind_BACL = 57 
  INTEGER, PARAMETER :: ind_N2O5 = 58 
  INTEGER, PARAMETER :: ind_SO2 = 59 
  INTEGER, PARAMETER :: ind_HONO = 60 
  INTEGER, PARAMETER :: ind_DMS = 61 
  INTEGER, PARAMETER :: ind_ALK5 = 62 
  INTEGER, PARAMETER :: ind_ALK3 = 63 
  INTEGER, PARAMETER :: ind_TBU_O = 64 
  INTEGER, PARAMETER :: ind_COOH = 65 
  INTEGER, PARAMETER :: ind_HOCOO = 66 
  INTEGER, PARAMETER :: ind_BZNO2_O = 67 
  INTEGER, PARAMETER :: ind_ARO2 = 68 
  INTEGER, PARAMETER :: ind_MEOH = 69 
  INTEGER, PARAMETER :: ind_HNO4 = 70 
  INTEGER, PARAMETER :: ind_ARO1 = 71 
  INTEGER, PARAMETER :: ind_DCB2 = 72 
  INTEGER, PARAMETER :: ind_DCB3 = 73 
  INTEGER, PARAMETER :: ind_CRES = 74 
  INTEGER, PARAMETER :: ind_ALK4 = 75 
  INTEGER, PARAMETER :: ind_C2H2 = 76 
  INTEGER, PARAMETER :: ind_DCB1 = 77 
  INTEGER, PARAMETER :: ind_NPHE = 78 
  INTEGER, PARAMETER :: ind_ROOH = 79 
  INTEGER, PARAMETER :: ind_BALD = 80 
  INTEGER, PARAMETER :: ind_PHEN = 81 
  INTEGER, PARAMETER :: ind_MGLY = 82 
  INTEGER, PARAMETER :: ind_CO = 83 
  INTEGER, PARAMETER :: ind_HNO3 = 84 
  INTEGER, PARAMETER :: ind_ETHENE = 85 
  INTEGER, PARAMETER :: ind_ACET = 86 
  INTEGER, PARAMETER :: ind_C3H6 = 87 
  INTEGER, PARAMETER :: ind_GLY = 88 
  INTEGER, PARAMETER :: ind_BZ_O = 89 
  INTEGER, PARAMETER :: ind_OLE1 = 90 
  INTEGER, PARAMETER :: ind_TERP = 91 
  INTEGER, PARAMETER :: ind_R2O2 = 92 
  INTEGER, PARAMETER :: ind_SESQ = 93 
  INTEGER, PARAMETER :: ind_ISOPRENE = 94 
  INTEGER, PARAMETER :: ind_METHACRO = 95 
  INTEGER, PARAMETER :: ind_ISOPROD = 96 
  INTEGER, PARAMETER :: ind_CCHO = 97 
  INTEGER, PARAMETER :: ind_OLE2 = 98 
  INTEGER, PARAMETER :: ind_MVK = 99 
  INTEGER, PARAMETER :: ind_HCHO = 100 
  INTEGER, PARAMETER :: ind_RNO3 = 101 
  INTEGER, PARAMETER :: ind_O3P = 102 
  INTEGER, PARAMETER :: ind_RCHO = 103 
  INTEGER, PARAMETER :: ind_MEK = 104 
  INTEGER, PARAMETER :: ind_PROD2 = 105 
  INTEGER, PARAMETER :: ind_O3 = 106 
  INTEGER, PARAMETER :: ind_RO2_R = 107 
  INTEGER, PARAMETER :: ind_RCO_O2 = 108 
  INTEGER, PARAMETER :: ind_NO2 = 109 
  INTEGER, PARAMETER :: ind_C_O2 = 110 
  INTEGER, PARAMETER :: ind_CCO_O2 = 111 
  INTEGER, PARAMETER :: ind_HO2 = 112 
  INTEGER, PARAMETER :: ind_RO2_N = 113 
  INTEGER, PARAMETER :: ind_OH = 114 
  INTEGER, PARAMETER :: ind_NO = 115 
  INTEGER, PARAMETER :: ind_MA_RCO3 = 116 
  INTEGER, PARAMETER :: ind_BZCO_O2 = 117 
  INTEGER, PARAMETER :: ind_NO3 = 118 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 119 
  INTEGER, PARAMETER :: ind_M = 120 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE saprc99_mosaic_4bin_iepox_vbs_aq_Parameters

